title: Work in progress website
author: Edward Ballard
email: ECBTraining@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 New website for training purposes and increased working pace.

# social links
twitter_username: None
github_username:  None

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
